/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutDiagnosticRouteImport } from './routes/_layout/diagnostic'
import { Route as LayoutLearningPathRouteImport } from './routes/_layout/learning-path'
import { Route as LayoutMisionesRouteImport } from './routes/_layout/misiones'
import { Route as LayoutResultsRouteImport } from './routes/_layout/results'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDiagnosticRoute = LayoutDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLearningPathRoute = LayoutLearningPathRouteImport.update({
  id: '/learning-path',
  path: '/learning-path',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMisionesRoute = LayoutMisionesRouteImport.update({
  id: '/misiones',
  path: '/misiones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsRoute = LayoutResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/diagnostic': typeof LayoutDiagnosticRoute
  '/learning-path': typeof LayoutLearningPathRoute
  '/misiones': typeof LayoutMisionesRoute
  '/results': typeof LayoutResultsRoute
}
export interface FileRoutesByTo {
  '/diagnostic': typeof LayoutDiagnosticRoute
  '/learning-path': typeof LayoutLearningPathRoute
  '/misiones': typeof LayoutMisionesRoute
  '/results': typeof LayoutResultsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/diagnostic': typeof LayoutDiagnosticRoute
  '/_layout/learning-path': typeof LayoutLearningPathRoute
  '/_layout/misiones': typeof LayoutMisionesRoute
  '/_layout/results': typeof LayoutResultsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnostic' | '/learning-path' | '/misiones' | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/diagnostic' | '/learning-path' | '/misiones' | '/results' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/diagnostic'
    | '/_layout/learning-path'
    | '/_layout/misiones'
    | '/_layout/results'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/diagnostic': {
      id: '/_layout/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof LayoutDiagnosticRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/learning-path': {
      id: '/_layout/learning-path'
      path: '/learning-path'
      fullPath: '/learning-path'
      preLoaderRoute: typeof LayoutLearningPathRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/misiones': {
      id: '/_layout/misiones'
      path: '/misiones'
      fullPath: '/misiones'
      preLoaderRoute: typeof LayoutMisionesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results': {
      id: '/_layout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof LayoutResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDiagnosticRoute: typeof LayoutDiagnosticRoute
  LayoutLearningPathRoute: typeof LayoutLearningPathRoute
  LayoutMisionesRoute: typeof LayoutMisionesRoute
  LayoutResultsRoute: typeof LayoutResultsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDiagnosticRoute: LayoutDiagnosticRoute,
  LayoutLearningPathRoute: LayoutLearningPathRoute,
  LayoutMisionesRoute: LayoutMisionesRoute,
  LayoutResultsRoute: LayoutResultsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
